services:
    app:
        build: .
        ports:
            - "8080:8000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: api_travel_php
            DB_USERNAME: root
            DB_PASSWORD: mysecretpassword

    db:
        image: postgres:15
        environment:
            POSTGRES_DB: api_travel_php
            POSTGRES_USER: root
            POSTGRES_PASSWORD: mysecretpassword
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "root" ]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    pgdata:
